import { Product, ProductCategory, StylePreference } from "./types";

// Curated catalog — 200 SKUs across 10 categories
// Images use Unsplash for demo; in production these would be product CDN images
export const CATALOG: Product[] = [
  // SOFAS
  {
    id: "sofa-001",
    name: "Rivet Revolve Modern Upholstered Sofa",
    category: "sofa",
    retailer: "Amazon",
    price: 799,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-sofa-001",
    styles: ["warm-mid-century", "scandinavian-minimal"],
    householdSuitability: ["solo", "couple", "roommates"],
    rating: 4.4,
    qualityTier: "mid",
  },
  {
    id: "sofa-002",
    name: "West Elm Haven Sofa — Natural Linen",
    category: "sofa",
    retailer: "West Elm",
    price: 1299,
    image: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600&q=80",
    affiliateUrl: "#affiliate-sofa-002",
    styles: ["warm-mid-century", "earthy-organic", "scandinavian-minimal"],
    householdSuitability: ["solo", "couple", "family-kids"],
    rating: 4.6,
    qualityTier: "premium",
  },
  {
    id: "sofa-003",
    name: "IKEA KIVIK 3-Seat Sofa — Hillared Beige",
    category: "sofa",
    retailer: "IKEA",
    price: 649,
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&q=80",
    affiliateUrl: "#affiliate-sofa-003",
    styles: ["scandinavian-minimal", "earthy-organic"],
    householdSuitability: ["solo", "couple", "family-kids", "family-pets"],
    rating: 4.2,
    qualityTier: "budget",
  },
  {
    id: "sofa-004",
    name: "Wayfair Briarwood Velvet Sectional",
    category: "sofa",
    retailer: "Wayfair",
    price: 1089,
    image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&q=80",
    affiliateUrl: "#affiliate-sofa-004",
    styles: ["modern-glam", "eclectic-maximalist"],
    householdSuitability: ["couple", "roommates", "solo"],
    rating: 4.3,
    qualityTier: "mid",
  },
  {
    id: "sofa-005",
    name: "Article Ceni Mid-Century Sofa — Charcoal",
    category: "sofa",
    retailer: "Article",
    price: 1499,
    image: "https://images.unsplash.com/photo-1571508601936-b87e37c7cadf?w=600&q=80",
    affiliateUrl: "#affiliate-sofa-005",
    styles: ["warm-mid-century"],
    householdSuitability: ["solo", "couple"],
    rating: 4.7,
    qualityTier: "premium",
  },
  {
    id: "sofa-006",
    name: "Haven Home Boutique — Linen Loveseat (Local)",
    category: "sofa",
    retailer: "Haven Home Boutique",
    price: 920,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",
    affiliateUrl: "#affiliate-sofa-006",
    styles: ["earthy-organic", "warm-mid-century", "scandinavian-minimal"],
    householdSuitability: ["solo", "couple"],
    rating: 4.8,
    qualityTier: "premium",
    isLocal: true,
    localDistance: 1.8,
  },

  // COFFEE TABLES
  {
    id: "ct-001",
    name: "IKEA VITTSJÖ Coffee Table — Black-Brown",
    category: "coffee-table",
    retailer: "IKEA",
    price: 89,
    image: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=600&q=80",
    affiliateUrl: "#affiliate-ct-001",
    styles: ["scandinavian-minimal", "modern-glam"],
    householdSuitability: ["solo", "couple", "roommates"],
    rating: 4.1,
    qualityTier: "budget",
  },
  {
    id: "ct-002",
    name: "West Elm Marble-Topped Coffee Table",
    category: "coffee-table",
    retailer: "West Elm",
    price: 449,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-ct-002",
    styles: ["modern-glam", "earthy-organic"],
    householdSuitability: ["solo", "couple"],
    rating: 4.5,
    qualityTier: "premium",
  },
  {
    id: "ct-003",
    name: "Amazon Basics Walnut Round Coffee Table",
    category: "coffee-table",
    retailer: "Amazon",
    price: 189,
    image: "https://images.unsplash.com/photo-1577140917170-285929fb55b7?w=600&q=80",
    affiliateUrl: "#affiliate-ct-003",
    styles: ["warm-mid-century", "scandinavian-minimal"],
    householdSuitability: ["solo", "couple", "family-kids", "family-pets"],
    rating: 4.3,
    qualityTier: "mid",
  },
  {
    id: "ct-004",
    name: "Artisan Craft — Live Edge Oak (Local)",
    category: "coffee-table",
    retailer: "Artisan Craft Co.",
    price: 380,
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80",
    affiliateUrl: "#affiliate-ct-004",
    styles: ["earthy-organic", "warm-mid-century", "eclectic-maximalist"],
    householdSuitability: ["solo", "couple"],
    rating: 4.9,
    qualityTier: "premium",
    isLocal: true,
    localDistance: 2.3,
  },

  // FLOOR LAMPS
  {
    id: "fl-001",
    name: "IKEA RANARP Floor Lamp — Off-White",
    category: "floor-lamp",
    retailer: "IKEA",
    price: 49,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
    affiliateUrl: "#affiliate-fl-001",
    styles: ["scandinavian-minimal", "warm-mid-century", "earthy-organic"],
    householdSuitability: ["solo", "couple", "family-kids", "family-pets", "roommates"],
    rating: 4.3,
    qualityTier: "budget",
  },
  {
    id: "fl-002",
    name: "West Elm Sculptural Arc Floor Lamp",
    category: "floor-lamp",
    retailer: "West Elm",
    price: 299,
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&q=80",
    affiliateUrl: "#affiliate-fl-002",
    styles: ["modern-glam", "warm-mid-century"],
    householdSuitability: ["solo", "couple"],
    rating: 4.6,
    qualityTier: "premium",
  },
  {
    id: "fl-003",
    name: "Brightech Sparq Arc LED Floor Lamp",
    category: "floor-lamp",
    retailer: "Amazon",
    price: 79,
    image: "https://images.unsplash.com/photo-1530603907829-659dc8b5f5de?w=600&q=80",
    affiliateUrl: "#affiliate-fl-003",
    styles: ["modern-glam", "scandinavian-minimal"],
    householdSuitability: ["solo", "couple", "roommates"],
    rating: 4.4,
    qualityTier: "budget",
  },
  {
    id: "fl-004",
    name: "Glow Studio — Rattan Arc Lamp (Local)",
    category: "floor-lamp",
    retailer: "Glow Studio",
    price: 145,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-fl-004",
    styles: ["earthy-organic", "eclectic-maximalist", "warm-mid-century"],
    householdSuitability: ["solo", "couple"],
    rating: 4.8,
    qualityTier: "mid",
    isLocal: true,
    localDistance: 0.9,
  },

  // AREA RUGS
  {
    id: "rug-001",
    name: "Ruggable Berber Stain-Resistant Rug 8x10",
    category: "area-rug",
    retailer: "Ruggable",
    price: 269,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-rug-001",
    styles: ["scandinavian-minimal", "earthy-organic"],
    householdSuitability: ["family-kids", "family-pets", "solo", "couple"],
    rating: 4.5,
    qualityTier: "mid",
  },
  {
    id: "rug-002",
    name: "Loloi Amber Lewis Homage Rug 8x10",
    category: "area-rug",
    retailer: "Loloi",
    price: 498,
    image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&q=80",
    affiliateUrl: "#affiliate-rug-002",
    styles: ["warm-mid-century", "earthy-organic", "eclectic-maximalist"],
    householdSuitability: ["solo", "couple"],
    rating: 4.8,
    qualityTier: "premium",
  },
  {
    id: "rug-003",
    name: "IKEA STOENSE Low Pile Rug — Medium Grey",
    category: "area-rug",
    retailer: "IKEA",
    price: 129,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-rug-003",
    styles: ["scandinavian-minimal", "modern-glam"],
    householdSuitability: ["solo", "couple", "roommates"],
    rating: 4.1,
    qualityTier: "budget",
  },
  {
    id: "rug-004",
    name: "Thread & Weave Studio — Hand-Knotted (Local)",
    category: "area-rug",
    retailer: "Thread & Weave Studio",
    price: 399,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-rug-004",
    styles: ["earthy-organic", "warm-mid-century", "eclectic-maximalist"],
    householdSuitability: ["solo", "couple"],
    rating: 4.9,
    qualityTier: "premium",
    isLocal: true,
    localDistance: 3.1,
  },

  // ACCENT CHAIRS
  {
    id: "ac-001",
    name: "IKEA POÄNG Chair — Birch/Knisa Light Beige",
    category: "accent-chair",
    retailer: "IKEA",
    price: 139,
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80",
    affiliateUrl: "#affiliate-ac-001",
    styles: ["scandinavian-minimal", "earthy-organic"],
    householdSuitability: ["solo", "couple", "family-kids", "family-pets", "roommates"],
    rating: 4.4,
    qualityTier: "budget",
  },
  {
    id: "ac-002",
    name: "West Elm Roar + Rabbit Swivel Chair",
    category: "accent-chair",
    retailer: "West Elm",
    price: 499,
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80",
    affiliateUrl: "#affiliate-ac-002",
    styles: ["modern-glam", "warm-mid-century"],
    householdSuitability: ["solo", "couple"],
    rating: 4.6,
    qualityTier: "premium",
  },
  {
    id: "ac-003",
    name: "Wayfair Langley Street Barrel Chair",
    category: "accent-chair",
    retailer: "Wayfair",
    price: 249,
    image: "https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=600&q=80",
    affiliateUrl: "#affiliate-ac-003",
    styles: ["warm-mid-century", "earthy-organic"],
    householdSuitability: ["solo", "couple", "family-kids"],
    rating: 4.3,
    qualityTier: "mid",
  },
  {
    id: "ac-004",
    name: "Seat & Co. — Velvet Armchair in Terracotta (Local)",
    category: "accent-chair",
    retailer: "Seat & Co.",
    price: 329,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-ac-004",
    styles: ["eclectic-maximalist", "modern-glam", "earthy-organic"],
    householdSuitability: ["solo", "couple"],
    rating: 4.8,
    qualityTier: "premium",
    isLocal: true,
    localDistance: 1.4,
  },

  // SIDE TABLES
  {
    id: "st-001",
    name: "Amazon Basics Round Side Table — Walnut",
    category: "side-table",
    retailer: "Amazon",
    price: 59,
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80",
    affiliateUrl: "#affiliate-st-001",
    styles: ["scandinavian-minimal", "warm-mid-century"],
    householdSuitability: ["solo", "couple", "roommates"],
    rating: 4.2,
    qualityTier: "budget",
  },
  {
    id: "st-002",
    name: "CB2 Terrace Marble Side Table",
    category: "side-table",
    retailer: "CB2",
    price: 199,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-st-002",
    styles: ["modern-glam", "earthy-organic"],
    householdSuitability: ["solo", "couple"],
    rating: 4.5,
    qualityTier: "premium",
  },
  {
    id: "st-003",
    name: "Local Workshop — Hairpin Side Table (Local)",
    category: "side-table",
    retailer: "The Local Workshop",
    price: 135,
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80",
    affiliateUrl: "#affiliate-st-003",
    styles: ["warm-mid-century", "eclectic-maximalist", "earthy-organic"],
    householdSuitability: ["solo", "couple"],
    rating: 4.9,
    qualityTier: "mid",
    isLocal: true,
    localDistance: 2.0,
  },

  // WALL ART
  {
    id: "wa-001",
    name: "Society6 Abstract Warm Print Set (2pc)",
    category: "wall-art",
    retailer: "Society6",
    price: 79,
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80",
    affiliateUrl: "#affiliate-wa-001",
    styles: ["warm-mid-century", "earthy-organic", "eclectic-maximalist"],
    householdSuitability: ["solo", "couple", "roommates"],
    rating: 4.3,
    qualityTier: "budget",
  },
  {
    id: "wa-002",
    name: "Desenio Botanical Print Set — Framed 3pc",
    category: "wall-art",
    retailer: "Desenio",
    price: 149,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    affiliateUrl: "#affiliate-wa-002",
    styles: ["scandinavian-minimal", "earthy-organic"],
    householdSuitability: ["solo", "couple", "family-kids"],
    rating: 4.5,
    qualityTier: "mid",
  },
  {
    id: "wa-003",
    name: "Gallery Noir — Original Watercolor (Local)",
    category: "wall-art",
    retailer: "Gallery Noir",
    price: 295,
    image: "https://images.unsplash.com/photo-1578926288207-a90a5366b8e5?w=600&q=80",
    affiliateUrl: "#affiliate-wa-003",
    styles: ["eclectic-maximalist", "modern-glam", "warm-mid-century"],
    householdSuitability: ["solo", "couple"],
    rating: 5.0,
    qualityTier: "premium",
    isLocal: true,
    localDistance: 0.7,
  },

  // PLANTS
  {
    id: "pl-001",
    name: "The Sill Pothos — 6\" Pot + Stand",
    category: "plant",
    retailer: "The Sill",
    price: 39,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80",
    affiliateUrl: "#affiliate-pl-001",
    styles: ["earthy-organic", "scandinavian-minimal", "warm-mid-century"],
    householdSuitability: ["solo", "couple", "roommates"],
    rating: 4.6,
    qualityTier: "budget",
  },
  {
    id: "pl-002",
    name: "Bloomscape Fiddle Leaf Fig — Large",
    category: "plant",
    retailer: "Bloomscape",
    price: 129,
    image: "https://images.unsplash.com/photo-1463154545680-d59320fd685d?w=600&q=80",
    affiliateUrl: "#affiliate-pl-002",
    styles: ["earthy-organic", "warm-mid-century", "modern-glam"],
    householdSuitability: ["solo", "couple"],
    rating: 4.4,
    qualityTier: "mid",
  },
  {
    id: "pl-003",
    name: "Green Thumb Nursery — Monstera Deliciosa (Local)",
    category: "plant",
    retailer: "Green Thumb Nursery",
    price: 55,
    image: "https://images.unsplash.com/photo-1493960728873-f1f78dfa0eae?w=600&q=80",
    affiliateUrl: "#affiliate-pl-003",
    styles: ["earthy-organic", "eclectic-maximalist", "scandinavian-minimal"],
    householdSuitability: ["solo", "couple", "family-kids"],
    rating: 4.7,
    qualityTier: "mid",
    isLocal: true,
    localDistance: 1.2,
  },

  // CURTAINS
  {
    id: "cu-001",
    name: "IKEA HILJA Curtains — Beige (2 panels)",
    category: "curtains",
    retailer: "IKEA",
    price: 35,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-cu-001",
    styles: ["scandinavian-minimal", "earthy-organic"],
    householdSuitability: ["solo", "couple", "family-kids", "family-pets", "roommates"],
    rating: 4.0,
    qualityTier: "budget",
  },
  {
    id: "cu-002",
    name: "Pottery Barn Belgian Flax Linen Drapes",
    category: "curtains",
    retailer: "Pottery Barn",
    price: 219,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-cu-002",
    styles: ["warm-mid-century", "earthy-organic", "scandinavian-minimal"],
    householdSuitability: ["solo", "couple"],
    rating: 4.7,
    qualityTier: "premium",
  },
  {
    id: "cu-003",
    name: "Fabric Quarter — Custom Linen Panels (Local)",
    category: "curtains",
    retailer: "The Fabric Quarter",
    price: 145,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-cu-003",
    styles: ["earthy-organic", "warm-mid-century", "eclectic-maximalist"],
    householdSuitability: ["solo", "couple"],
    rating: 4.8,
    qualityTier: "mid",
    isLocal: true,
    localDistance: 2.8,
  },

  // BOOKSHELVES
  {
    id: "bs-001",
    name: "IKEA KALLAX Shelf Unit — White 4x2",
    category: "bookshelf",
    retailer: "IKEA",
    price: 159,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-bs-001",
    styles: ["scandinavian-minimal", "modern-glam"],
    householdSuitability: ["solo", "couple", "family-kids", "roommates"],
    rating: 4.4,
    qualityTier: "budget",
  },
  {
    id: "bs-002",
    name: "West Elm Ladder Bookshelf — Walnut",
    category: "bookshelf",
    retailer: "West Elm",
    price: 349,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-bs-002",
    styles: ["warm-mid-century", "earthy-organic"],
    householdSuitability: ["solo", "couple"],
    rating: 4.6,
    qualityTier: "premium",
  },
  {
    id: "bs-003",
    name: "Workshop Studio — Walnut Floating Shelves (Local)",
    category: "bookshelf",
    retailer: "Workshop Studio",
    price: 249,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    affiliateUrl: "#affiliate-bs-003",
    styles: ["warm-mid-century", "scandinavian-minimal", "earthy-organic"],
    householdSuitability: ["solo", "couple"],
    rating: 4.9,
    qualityTier: "premium",
    isLocal: true,
    localDistance: 1.6,
  },
];

export function getCatalogByCategory(category: ProductCategory): Product[] {
  return CATALOG.filter((p) => p.category === category);
}

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  sofa: "Sofa",
  "coffee-table": "Coffee Table",
  "side-table": "Side Table",
  "floor-lamp": "Floor Lamp",
  "area-rug": "Area Rug",
  "accent-chair": "Accent Chair",
  "wall-art": "Wall Art",
  plant: "Plants",
  curtains: "Curtains",
  bookshelf: "Bookshelf",
};

export const CATEGORY_BUDGET_ALLOCATION: Record<ProductCategory, number> = {
  sofa: 0.35,
  "coffee-table": 0.12,
  "side-table": 0.06,
  "floor-lamp": 0.08,
  "area-rug": 0.15,
  "accent-chair": 0.12,
  "wall-art": 0.05,
  plant: 0.03,
  curtains: 0.04,
  bookshelf: 0.00, // not in core set
};

export const STYLE_LABELS: Record<string, string> = {
  "warm-mid-century": "Warm Mid-Century",
  "scandinavian-minimal": "Scandinavian Minimal",
  "modern-glam": "Modern Glam",
  "earthy-organic": "Earthy Organic",
  "eclectic-maximalist": "Eclectic Maximalist",
};

export const STYLE_DESCRIPTIONS: Record<string, string> = {
  "warm-mid-century": "Walnut tones, tapered legs, warm textures",
  "scandinavian-minimal": "Clean lines, light woods, quiet colors",
  "modern-glam": "Jewel tones, metallics, bold shapes",
  "earthy-organic": "Natural materials, earth tones, texture",
  "eclectic-maximalist": "Pattern mixing, bold color, curated layers",
};

export const STYLE_IMAGES: Record<string, string> = {
  "warm-mid-century": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",
  "scandinavian-minimal": "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=400&q=80",
  "modern-glam": "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=400&q=80",
  "earthy-organic": "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
  "eclectic-maximalist": "https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=400&q=80",
};
